### ISSUE TITLE
Email stylen, die vom Kontaktformular von der Website kommt

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#24]
## Value statement - a requirement, not a solution
As a **secretary** 
I need **a nice looking email from nodemailer** 
so that **I don't hate my job, when i read these typewriter-looking emails** 

### From this:
![grafik](https://user-images.githubusercontent.com/54703643/106400956-ca8f0100-6421-11eb-80e6-78e2c5814030.png)
### to something like this, but with style from the site
![grafik](https://user-images.githubusercontent.com/54703643/106400988-ed211a00-6421-11eb-8a8c-62dc5b5e055f.png)

## Acceptance criteria
- [ ] (functional descriptions)

## Tasks
- [ ] (todos for the team)

## Size
(medium)

**Comment by oooppi** [comment]
Bisher haben wir das Email Kontaktformular als Mail zu unserem Standartmailprogram von Windows bekommen. Die Variante oben kannst du gerne einbauen, sieht gut aus ;). Hier ist auch unsere Standart Schriftart. Die bitte auf der Homepage verwenden. 

[Schriftarten.zip](https://github.com/mpagels/nordlichter-website/files/5917395/Schriftarten.zip)

**Comment by mpagels** [comment]
Wird parallel hiermit #44 bearbeitet.

**Comment by mpagels** [comment]
@oooppi 
Das wäre eine Design Entwurf, die die Rezeption bekommen würde, wenn jemand über die Website das Formular benutzen würde.

Du kannst die Rezeption ja mal fragen was noch so benötigt wird bzw. damit man schnell erfassen kann was der Patient will/brauch, damit die Arbeit am einfachsten für alle ist. 

Als Bsp.: Private Verordnungen soll nicht ein blauer Hintergrund sein, sondern zb. rot. 

![Bildschirmfoto 2021-03-03 um 17 17 39](https://user-images.githubusercontent.com/54703643/109836555-8ec7a100-7c44-11eb-9108-956587d67ef3.png)
