### ISSUE TITLE
Der Link geht nicht

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mpagels** [comment]
Ahhh ich hjabe da noch mal ne Fräge!

## Frage

**Comment by oooppi** [comment]
Wozu bezahl ich dich eigentlich? Mach!

**Comment by mpagels** [comment]
Link ist gefixt, hier der Link zur Preview Website

**Comment by soerenstein** [comment]
> Link ist gefixt, hier der Link zur Preview Website

So schnell bekomme ich nichtmal die GitHub-Benachrichtigungen, wie du die Probleme löst. ☹️
