### ISSUE TITLE
Logo zu grob aufgelöst

### ISSUE THREAD

**Issue by oooppi** [mpagels/nordlichter-website#29]
**Describe the bug**
Logo Datei muss getauscht werden

**To Reproduce**
1. Go to Start seite

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

- [ ] Oppi hat neues hochauflösendes Logo geliefert- 
- [ ] Logo ist in Website eingebunden
- [ ] Oppi hat neues Logo für OK auf Website befunden

**Comment by mpagels** [comment]
Duplicate of #23

**Comment by oooppi** [comment]
Neue  Grafik Datei folgt

**Comment by oooppi** [comment]
![Nordlichter_Logo_0817](https://user-images.githubusercontent.com/78348784/106725441-ab52c800-6609-11eb-8316-87aa4790a4a4.jpg)
![Nordlichter_Logo_0817_web](https://user-images.githubusercontent.com/78348784/106725466-b3ab0300-6609-11eb-8b3a-7d990947f571.png)
![Nordlichter_Anker](https://user-images.githubusercontent.com/78348784/106725486-ba397a80-6609-11eb-97d9-4a80a2781d2e.jpg)

**Comment by oooppi** [comment]
Diese Grafiken müssten besser dargestellt werden als das vorhandene. Der Anker kann hier und da ebenfalls eingebaut werden

**Comment by mpagels** [comment]
Das blau sieht in dem oberen Image ziemlich komisch aus.

**Comment by oooppi** [comment]
Die oberste Grafik ist die CMYK Datei. Also nicht brauchbar. Die mittlere Grafik sollte benutzt werden

**Comment by mpagels** [comment]
@oooppi 
Ich habe das neue hochauflösende Logo eingebunden. Bitte einmal kontrollieren:
[website](https://nordlichter-website-m5juqpn5n.vercel.app/)

**Comment by mpagels** [comment]
Closed. Logo ist eingebunden.
