### ISSUE TITLE
E-Mail Adresse ist falsch

### ISSUE THREAD

**Issue by oooppi** [mpagels/nordlichter-website#39]
**Describe the bug**
Falsche Kontaktemail (infos@nordlichter-halstenbek.de)

Korrekt: info@nordlichter-halstenbek.de

**Comment by mpagels** [comment]
Brauche mehr Infos. Wo hast du die Email gesehen? Wo muss sie auf der Website geändert werden?

**Comment by oooppi** [comment]
![grafik](https://user-images.githubusercontent.com/78348784/106728439-bb1fdb80-660c-11eb-8ccd-0ccbd23f3ffa.png)

**Comment by mpagels** [comment]
Nice. Perfekt.

**Comment by mpagels** [comment]
@oooppi 
Ich habe die Email geändert. Hier bitte einmal kontrollieren:
[website](https://nordlichter-website-m5juqpn5n.vercel.app/)

**Comment by mpagels** [comment]
Closes. Email wurde geändert.
