### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by oooppi** [mpagels/nordlichter-website#41]
Neuer Aufbau der Landing Page

Grundsätzlich soll die Landing Page als erster Kontakt für den Neukunden erstellt werden. Hier soll der Kunde einen Link für ein Gratisvideo erhalten womit er einerseits eine erste Dienstleistung von uns erhält und andererseits seine Daten für gezielte Marketing Maßnahmen hinterlassen kann. Der fortlaufende Prozess zielt hier auf den Vertrieb von weiteren, zukünftigen Info Produkten hin. Er hat auch jederzeit die Möglichkeit, eine Terminanfrage für die Praxis abzuschicken.

**Comment by oooppi** [comment]
Zusatz unter "Vereinbaren Sie einen Termin"

Sie haben Fragen? Wir rufen Sie zurück --> Kontaktformular

**Comment by mpagels** [comment]
Alles klar. Ich muss aber noch mal nachfragen, um sicherzugehen:
Was ist für dich die Landingpage?

Ist das die Page, die der Besucher sieht, wenn er das erste Mal auf die Website geht? Also er tippt im Browser die URL von nordlichter ein und klickt Enter?

Und mir ist in deinem Konzept noch was aufgefallen:
Im Text sprichst du deine Website Besucher mit `Sie` an. Im Kontaktformular bist du dann plötzlich beim `Du`. Ist das von dir gewollt?

<img width="1178" alt="Bildschirmfoto 2021-03-31 um 13 12 17" src="https://user-images.githubusercontent.com/54703643/113136351-8d799c00-9223-11eb-9542-20b6f35f40d9.png">

**Comment by oooppi** [comment]
Korrektur Text:

Durch Ihre Eintragung bestätigen Sie, dass Sie gerne ab und zu unseren Newsletter bekommen,in dem Sie viel Know-how und Anregungen zu den Themen Gesundheit, Ernährung, Krankheitsvorbeugung und viele weitere interessante Informationen bekommen. Natürlich ebenfalls vollkommen kostenfrei.

**Comment by mpagels** [comment]
Der User gibt seine Daten ein
- Vorname pflicht
- Nachname pflicht
- email adresse pflicht
- telefonnummer optional (damit wir sie bei probleme erreichen können)

Der Abschick-button ist erst grau, wird dann aktiv wenn alle Daten korrekt eingegeben sind.
Der User klickt auf "abschicken" die Daten werden an den Server geschickt!

Es öffnet sich ein popup, da steht drauf, Wir haben ihre email erhalten, wir schicken ihne einen Bestätigungslink zu.

Dann email mit bestätigungslink, da muss der User ein letztes mal bestätigen, dass er den Newsletter auch wirklich haben will.

Danach schickt der Server eine weitere Email mit dem Link zum Video.

**Comment by oooppi** [comment]
[Startseite.pdf](https://github.com/mpagels/nordlichter-website/files/6271107/Startseite.pdf)

**Comment by oooppi** [comment]
![Anker](https://user-images.githubusercontent.com/78348784/116781187-b474f900-aa81-11eb-8de6-749eb80fbe21.jpg)
![Nordlichter_Anker](https://user-images.githubusercontent.com/78348784/116781188-b474f900-aa81-11eb-9ed8-d0b1e881575e.jpg)


Schau mal ob du damit arbeiten kannst. Sonst sag einfach bescheid




![Nordlichter_Logo_0817](https://user-images.githubusercontent.com/78348784/116781184-b17a0880-aa81-11eb-9a3e-1c4caac9cae2.png)

**Comment by mpagels** [comment]
@oooppi hattest du nicht gesagt, dass du auch eine `eps` Datei gibt?

**Comment by mpagels** [comment]
Alles, was hier drin steht, wurde erledigt, bzw. ist nicht mehr aktuell.
