### ISSUE TITLE
Kontaktformular ändern

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#44]
## Wertaussage - Eine Anforderung, keine Lösung
Als ein **User** 
brauche ich **im Kontaktformular eine Auswahlmöglichkeit** 
so dass ich **entweder einfach nur eine Frage stellen kann oder Infos zu einem Termin übergeben kann** 

## Beschreibung (Text, Zeichnung, Wireframe, Design)
Um zwei Fliegen mit einer Klappe zu schlagen, wollen wir im Formular die Möglichkeit geben, per Auswahl ein normales Fragenformular anzuzeigen oder einen Termin anzufragen. Jeder dieser Auswahlmöglichkeiten bieten dem User unterschiedliche Inputs die er verwenden kann.

## Akzeptanzkriterien
- [x] Der User kann auswählen bei **Ich** `habe eine Frage` oder `interessiere mich für einen Termin`
- [x] Es ist ein Auswahlbutton, wenn der jeweilige Button geklickt wird, wird das eine oder das andere Formular angezeigt 
- [x] Das Kontaktforumlar wacht immer mit folgenden Input auf
- [x] Vor- und Nachname
- [x] Telefonnummer
- [x] Email
- [x] Textfeld
Bei Terminanfrage kommt noch hinzu
- [x] Auswahlbutton:
- [x] Ich habe `Keine Verodnung`
- [x] Ich habe `Eine gesetzliche Verordnung`
- [x] Ich habe `Eine private Verordnung`
- [x] Es gibt eine Dropdown Listenauswahl, wenn man eine Verordnung hat
- [x] Ein Abschick Button
- [x] Nach anklicken des Buttons, gibt es eine Nachricht, dass die Nachricht verschickt wurde
- [x] und das Formular verschwindet
- [ ] Ein `erneute Nachricht Schicken` Button, erscheint und bei klicken, verschwindet es und das Kontaktformular erscheint leer für erneutes eingeben

## Aufgaben
- [x]  @oooppi liefert Verordnungen für Liste an

## Aufwand
(mittel)

**Comment by oooppi** [comment]
Heilmittelliste für GKV (gesetzliche Krankenkasse) Verordnungen:

- Krankengymnastik
- Manuelle Therapie
- Manuelle Lymphdrainage 30 Minuten
- Manuelle Lymphdrainage 45 Minuten
- Manuelle Lymphdrainage 60 Minuten
- Klassische Massagetherapie
- Bindegewebsmassage

Ergänzende Heilmittel:
- Wärmetherapie (Heissluft/Rotlicht/Infrarot)
- Warmpackungen (Fango/Moor)
- Heisse Rolle
- Kältetherapie

**Comment by mpagels** [comment]
Heilmittelleiste benötigt eine Funktion, ein PLUS, der gesetzliche Patient könnte nämlich zwei Verordnungen.
Notiz anzeigen, dass Praxis für weitere Infos (zb.: Anzahl der Heilmittel und Terminvereinbarung zurück ruft.

Private Patienten könnten theoretisch alle Heilmittel und alle Ergänzende Heilmittel verordnet bekommen haben, daher muss das für Privatpatienten auch auswählbar sein.

Selbstzahler hat keine Auwahlmöglichkeit und bekommt angezeigt, bitte alle Infos in Textfeld eingeben.

**Comment by oooppi** [comment]
@mpagels 

Kontaktformular um weitere Felder für geeignete Termine erweitern:

Nach den Verordnungsfeldern kann der Patient noch Wochentage und mögliche Zeiträume angeben um der Verwaltung noch mehr Informationen für mögliche Termine zu geben.

Tage (Montag - Freitag)
Zeiträume: 7-9 ; 9-12;12-15;15-19 (Freitags nur 15-18)

**Comment by soerenstein** [comment]
Ich habe eine QA in der Desktop-Ansicht des Kontaktformulars gemacht. Dabei ist mir eine Kleinigkeit aufgefallen: 

Wenn man in den rot markierten Bereich um die Radio-Button klickt, registriert der Button die Veränderung und es werden unterhalb andere Auswahlmöglichkeiten angezeigt. Der geklickte Radio-Button wird allerdings nicht markiert. Ist das bereits bekannt? 

![Bildschirmfoto 2021-04-28 um 13 10 44](https://user-images.githubusercontent.com/67868341/116395246-2b14bb00-a824-11eb-931e-ea0b08133ef4.png)

**Comment by mpagels** [comment]
Ja, ist mir auch schon aufgefallen. Das Kontaktformular benötigt eh eine kleine Focus Einheit. Da passieren noch ganz andere Dinge nicht passieren sollen. Da hier eh noch [Erweiterungen](https://github.com/mpagels/nordlichter-website/issues/44#issuecomment-822661270) geplant sind, wollte ich das in der Focus Zeit erledigen. Danke für den Reminder.
