### ISSUE TITLE
Landing Page für Video "Die 5 besten Tipps gegen Rückenbeschwerden"

### ISSUE THREAD

**Issue by oooppi** [mpagels/nordlichter-website#57]
[Aufbau Landing Page.pdf](https://github.com/mpagels/nordlichter-website/files/6273632/Aufbau.Landing.Page.pdf)

**Comment by mpagels** [comment]
Bin jetzt erst dazu gekommen da mal hereinzuschauen. Wie soll dass denn ablaufen? Der user gibt seine Informationen und klickt dann "absenden". und dann? Kriegt er das Video dann per Email?

**Comment by mpagels** [comment]
Component was removed with #75.
