### ISSUE TITLE
Selbstzahler

### ISSUE THREAD

**Issue by oooppi** [mpagels/nordlichter-website#59]
Du hattest damals schon einen sehr schönen Selbstzahler Bereich von den bestehenden Inhalten erstellt. Da war bereits ein sehr schönes Rabatt Feld bei den Abo gewesen usw.
Wenn du das so erstmal wieder einfügen kannst reicht das erstmal.
Wir wollen demnächst zwar die Preise verändern, das sind dann aber nur Korrekturen. Insgesamt verändert sich die Produktpalette nicht.

**Comment by mpagels** [comment]
Ist erledigt. #63
