### ISSUE TITLE
Partner Link zu Jobs ändern

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#65]
In der NavBar soll Partner zu Jobs geändert werden, die dann auf eine "Recruting" Seite leitet, wo Torben Stellenangebote posten, bzw. Informationen dazu.

**Comment by mpagels** [comment]
Ist diese "Recruiting" Seite extern oder bauen wir eine Job Seite auf der nortlichter website?

**Comment by oooppi** [comment]
Die bauen wir als eigene Seite auf unsere Page ein.

**Comment by mpagels** [comment]
Schließe ich erstmal. Merged in #70. Job Seite fehlt noch, wird später in extra Issue behandelt.
