### ISSUE TITLE
Fachbereiche in der Team "Akten" ändern.

### ISSUE THREAD

**Issue by mpagels** [mpagels/nordlichter-website#67]
Torben liefert Name und neue Texte

**Comment by mpagels** [comment]
Uhh die Idee gefällt mir. Kriegen wir eingebaut. Lass uns das am Mittwoch genauer besprechen.

**Comment by oooppi** [comment]
Denke mal die Grundidee ist klar oder? Dann geb ich dir hier schonmal die ersten Infos. Das Layout für das Foto und den Text überlasse ich deinen fähigen Händen. Die Anordung der Teammitglieder ist noch nicht die finale Reihenfolge

Torben Petersen-Lund
Physiotherapeut seit 2010
Nordlicht seit 2017

--> mehr Informationen

**Manuelle Lymphdrainage (2010)**
Kinesiotaping (2010)
Lymphtaping (2012)
zertifizierter Athletenbetreuer - DAASM (2012)
**Physiotherapeutische Betreuung im Leistungsport seit 2007**
Myofasciale Triggerpunkt Therapie (2013)
**Manuelle Therapie (2015)**
Ernährungsphysiologie und Beratung (2016)
**Gründung der Praxis "Die Nordlichter" in Halstenbek (2017)**

Kai Heinemann
Physiotherapeut seit 2010
Nordlicht seit 2019

--> mehr Informationen
**Manuelle Lymphdrainage (2010)**
Kinesiotaping (2010)
**Krankengymnastik am Gerät (2011)**
**Manuelle Therapie (2016)**
**PNF Fortbildung für physioneurologische Erkrankungen (2017)**
